# Markdown linting configuration for documentation
# Based on engineering best practices

# Extend base style
extends: markdownlint/style/prettier

# Rule customizations
rules:
  # Line length - handled by prettier, disable to avoid conflicts
  MD013: false

  # Allow inline HTML for advanced formatting (admonitions, etc.)
  MD033: false

  # First line doesn't need to be H1 (useful for templates and includes)
  MD041: false

  # Code block style - enforce fenced blocks
  MD046:
    style: fenced

  # Emphasis style - enforce consistent usage
  MD049:
    style: asterisk

  # Strong style - enforce consistent usage
  MD050:
    style: asterisk

  # Link fragments - allow for internal anchors
  MD051: false

  # Reference links - allow for cleaner docs
  MD052: false
