apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: react
  description: Documentation site for the repository, built with MkDocs and published with Backstage TechDocs.
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: ianlintner/React
spec:
  type: documentation
  owner: engineering
  lifecycle: experimental
