site_name: React Project Docs
site_description: Documentation for the project, structured for Backstage TechDocs
docs_dir: docs
use_directory_urls: true

nav:
  - Home: index.md
  - Getting Started:
      - Quickstart: getting-started/quickstart.md
      - Setup: getting-started/setup.md
      - Troubleshooting: getting-started/troubleshooting.md
  - Architecture:
      - System Overview: architecture/system-overview.md
      - Architecture Guide: architecture/architecture.md
      - Components:
          - Agents: architecture/components/agents.md
          - Backend: architecture/components/backend.md
          - Frontend: architecture/components/frontend.md
          - Message Queue: architecture/components/message-queue.md
          - RAG System: architecture/components/rag-system.md
          - Validation System: architecture/components/validation-system.md
  - Operations:
      - CI/CD: operations/ci-cd.md
      - Observability: operations/observability.md
      - Prometheus & Grafana: operations/prometheus-grafana.md
      - Tracing: operations/tracing.md
  - Reference:
      - API Reference: reference/api-reference.md
      - Code Quality: reference/code-quality.md
      - Docker Setup: reference/docker-setup.md
      - Test Bench: reference/test-bench.md
      - Test Bench OpenAPI: reference/test-bench-openapi.yaml
      - YouTube Embedding: reference/youtube-embedding.md
  - Examples:
      - External App: examples/external-app.md
  - Additional:
      - System Summary: system-summary.md
      - Backend (legacy): backend.md
      - API Reference (legacy): api-reference.md
      - Architecture (root doc): architecture.md
      - Docs README: README.md
      - IA Proposal: IA-PROPOSAL.md
      - Consolidation Plan: CONSOLIDATION-PLAN.md
      - Prometheus Grafana Migration: prometheus-grafana-migration.md
      - Docs Inventory (CSV): docs-inventory.csv

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - def_list
  - attr_list
  - fenced_code
  - codehilite:
      guess_lang: false
