site_name: AI Chat Demo - Technical Documentation
site_description: Enterprise-grade AI chat application documentation
docs_dir: docs
use_directory_urls: true

# SEO and metadata
site_author: Engineering Team
site_url: http://example-docs.hugecat.net/

# Enhanced theme configuration
theme:
  name: material
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/index.md
      - Quick Start: getting-started/quickstart.md
      - Development Setup: getting-started/setup.md
      - Troubleshooting: getting-started/troubleshooting.md
  - Architecture:
      - Overview: architecture/index.md
      - System Design: architecture/system-overview.md
      - Architecture Guide: architecture/architecture.md
      - Components:
          - Agent System: architecture/components/agents.md
          - Backend Services: architecture/components/backend.md
          - Frontend App: architecture/components/frontend.md
          - Message Queue: architecture/components/message-queue.md
          - RAG System: architecture/components/rag-system.md
          - Validation Pipeline: architecture/components/validation-system.md
      - Technical Decisions: architecture/decisions/README.md
  - Developer Guide:
      - API Reference: reference/api-reference.md
      - Code Quality Standards: reference/code-quality.md
      - Docker Setup: reference/docker-setup.md
      - Test Bench: reference/test-bench.md
      - YouTube Embedding: reference/youtube-embedding.md
  - Examples:
      - Code Samples: examples/code-samples.md
      - Integration Examples: examples/external-app.md
  - Operations:
      - Observability: operations/observability.md
      - Runbooks: operations/runbooks.md
      - CI/CD: operations/ci-cd.md
      - Monitoring: operations/prometheus-grafana.md
      - Tracing: operations/tracing.md

# Enhanced plugins
plugins:
  - techdocs-core
  - search:
      lang: en

# Enhanced markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: '¤'
      toc_depth: 3
  - pymdownx.betterem
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

# Enable strict mode for link checking
strict: true
