global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # OpenTelemetry Collector metrics
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # OpenTelemetry Collector exported metrics
  - job_name: 'otel-collector-exported'
    static_configs:
      - targets: ['otel-collector:8889']
    scrape_interval: 10s
    metrics_path: '/metrics'

  # AI Goal-Seeking System metrics (if we add a metrics endpoint)
  - job_name: 'ai-goal-seeking-system'
    static_configs:
      - targets: ['host.docker.internal:5001']
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s

  # Redis metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: '/metrics'
