apiVersion: builtin
kind: PatchTransformer
metadata:
  name: acme-service-to-infrastructure
patch: |-
  - op: replace
    path: /metadata/namespace
    value: default
target:
  group: cert-manager.io
  version: v1
  kind: Certificate
  name: chat-tls-cert
