apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: chat-frontend
  namespace: prod
spec:
  lifecycleRule:
    - action:
        type: Delete
      condition:
        age: 30
