apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-cni
  namespace: istio-system
spec:
  profile: default
  components:
    cni:
      enabled: true
  values:
    cni:
      cniBinDir: /home/kubernetes/bin
      cniConfDir: /etc/cni/net.d
      excludeNamespaces:
        - istio-system
        - kube-system
