apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: chat-dev-dns
  namespace: chat-dev
spec:
  name: chat-dev.hugecat.net.
  type: A
  ttl: 300
  rrdatas:
    - '34.123.45.67' # Replace with your LoadBalancer IP
  managedZoneRef:
    external: hugecat-zone # Replace with your actual Cloud DNS managed zone name
