apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: prod-workload-identity
  namespace: prod
spec:
  member: serviceAccount:kame-457417.svc.id.goog[prod/chat]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: prod-sa
