apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  labels:
    app: chat-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      serviceAccountName: chat
      containers:
        - name: chat-frontend
          image: us-central1-docker.pkg.dev/kame-457417/kame-house-images/chat-frontend:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: '250m'
              memory: '512Mi'
            limits:
              cpu: '500m'
              memory: '1Gi'
          env:
            - name: NODE_ENV
              value: 'production'
