apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  labels:
    app: chat-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      serviceAccountName: chat
      containers:
        - name: chat-frontend
          image: us-central1-docker.pkg.dev/kame-457417/kame-house-images/chat-frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            requests:
              cpu: '250m'
              memory: '512Mi'
            limits:
              cpu: '500m'
              memory: '1Gi'
          env:
            - name: NODE_ENV
              value: 'production'
