apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: chat-certificate
  labels:
    app: chat
spec:
  secretName: chat-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - 'chat.hugecat.net'
