apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  type: ExternalName
  externalName: chat-redis.us-central1.gce.redis.googleusercontent.com
  ports:
    - port: 6379
      targetPort: 6379
