name: GCP Auth Test

on:
  workflow_dispatch:

jobs:
  auth:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/316518955652/locations/global/workloadIdentityPools/github-pool/providers/github
          service_account: kame-house-oidc@kame-457417.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          universe: googleapis.com
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          id_token_include_email: false

      - name: Verify gcloud
        run: gcloud auth list
